// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611074757_AddUrunYeniAlanlar")]
    partial class AddUrunYeniAlanlar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ikon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Renk")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kadın",
                            Ikon = "fas fa-female",
                            Renk = "#EC4899"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Erkek",
                            Ikon = "fas fa-male",
                            Renk = "#1E3A5F"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Anne & Çocuk",
                            Ikon = "fas fa-baby",
                            Renk = "#F59E0B"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Ev & Yaşam",
                            Ikon = "fas fa-couch",
                            Renk = "#10B981"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Süpermarket",
                            Ikon = "fas fa-shopping-basket",
                            Renk = "#0EA5E9"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Kozmetik",
                            Ikon = "fas fa-gem",
                            Renk = "#8B5CF6"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Ayakkabı & Çanta",
                            Ikon = "fas fa-shoe-prints",
                            Renk = "#F43F5E"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Elektronik",
                            Ikon = "fas fa-laptop",
                            Renk = "#2563EB"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Saat & Aksesuar",
                            Ikon = "fas fa-clock",
                            Renk = "#78716C"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Spor & Outdoor",
                            Ikon = "fas fa-running",
                            Renk = "#EF4444"
                        });
                });

            modelBuilder.Entity("backend.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("backend.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Toplam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("backend.Models.SiparisDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisDetaylari");
                });

            modelBuilder.Entity("backend.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AltKategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Gorsel")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("IndirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IndirimYuzde")
                        .HasColumnType("int");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Marka")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<bool>("Stokta")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaksitAylikFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaksitSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("UcretsizKargo")
                        .HasColumnType("bit");

                    b.Property<string>("UrunTuru")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YorumSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Koton Siyah Kısa Elbise",
                            AltKategori = "Elbise",
                            Fiyat = 599m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 399m,
                            IndirimYuzde = 33,
                            Kategori = "kadin",
                            Marka = "Koton",
                            Puan = 4.0999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 89
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Mavi Beyaz Keten Gömlek",
                            AltKategori = "Üst Giyim",
                            Fiyat = 449m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 349m,
                            IndirimYuzde = 22,
                            Kategori = "kadin",
                            Marka = "Mavi",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 56
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Derimod Siyah Koton Pantolon",
                            AltKategori = "Alt Giyim",
                            Fiyat = 699m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "kadin",
                            Marka = "Derimod",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 34
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Tommy Hilfiger Lacivert Kaban",
                            AltKategori = "Dış Giyim",
                            Fiyat = 4999m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 3999m,
                            IndirimYuzde = 20,
                            Kategori = "kadin",
                            Marka = "Tommy Hilfiger",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 23
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Penti Siyah Külotlu Çorap 3lü",
                            AltKategori = "İç Giyim",
                            Fiyat = 89m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 69m,
                            IndirimYuzde = 22,
                            Kategori = "kadin",
                            Marka = "Penti",
                            Puan = 4.0,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 312
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Yüzme Bikini Takımı",
                            AltKategori = "Plaj",
                            Fiyat = 299m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 199m,
                            IndirimYuzde = 33,
                            Kategori = "kadin",
                            Marka = "Mudo",
                            Puan = 4.0999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 78
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Polo Mavi Klasik Gömlek",
                            AltKategori = "Gömlek",
                            Fiyat = 899m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 749m,
                            IndirimYuzde = 17,
                            Kategori = "erkek",
                            Marka = "Polo",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 78
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Mavi Jeans Siyah Dar Kot",
                            AltKategori = "Alt Giyim",
                            Fiyat = 799m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 599m,
                            IndirimYuzde = 25,
                            Kategori = "erkek",
                            Marka = "Mavi",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 112
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Koton Siyah Erkek Sweatshirt",
                            AltKategori = "Üst Giyim",
                            Fiyat = 349m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 249m,
                            IndirimYuzde = 29,
                            Kategori = "erkek",
                            Marka = "Koton",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 10,
                            Ad = "US POLO Lacivert Kaban",
                            AltKategori = "Dış Giyim",
                            Fiyat = 2999m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 2499m,
                            IndirimYuzde = 17,
                            Kategori = "erkek",
                            Marka = "US POLO",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 34
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Damat Tween Smokin Takım",
                            AltKategori = "Takım Elbise",
                            Fiyat = 5999m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 4999m,
                            IndirimYuzde = 17,
                            Kategori = "erkek",
                            Marka = "Damat Tween",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 12
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Pierre Cardin Kravat Seti",
                            AltKategori = "Aksesuar",
                            Fiyat = 199m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 149m,
                            IndirimYuzde = 25,
                            Kategori = "erkek",
                            Marka = "Pierre Cardin",
                            Puan = 4.0,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 89
                        },
                        new
                        {
                            Id = 13,
                            Ad = "Prima Bebek Bezi 4 Numara 84lü",
                            AltKategori = "Bebek Bezi",
                            Fiyat = 279m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 219m,
                            IndirimYuzde = 22,
                            Kategori = "anne-cocuk",
                            Marka = "Prima",
                            Puan = 4.7000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 1245
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Aptamil 2 Bebek Maması 800g",
                            AltKategori = "Bebek Maması",
                            Fiyat = 349m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 299m,
                            IndirimYuzde = 14,
                            Kategori = "anne-cocuk",
                            Marka = "Aptamil",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 890
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Lego Classic Yaratıcı Kutu",
                            AltKategori = "Oyuncak",
                            Fiyat = 599m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "anne-cocuk",
                            Marka = "Lego",
                            Puan = 4.7999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 234
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Nike Çocuk Spor Ayakkabı",
                            AltKategori = "Çocuk Giyim",
                            Fiyat = 1299m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 999m,
                            IndirimYuzde = 23,
                            Kategori = "anne-cocuk",
                            Marka = "Nike",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 17,
                            Ad = "Mustela Bebek Bakım Seti",
                            AltKategori = "Bebek Bakım",
                            Fiyat = 399m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 329m,
                            IndirimYuzde = 18,
                            Kategori = "anne-cocuk",
                            Marka = "Mustela",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 456
                        },
                        new
                        {
                            Id = 18,
                            Ad = "Philips Airfryer XXL 7L",
                            AltKategori = "Mutfak",
                            Fiyat = 5999m,
                            Gorsel = "/IMG/urun/Dyson-V15-Detect_1-removebg-preview.png",
                            IndirimFiyat = 4999m,
                            IndirimYuzde = 17,
                            Kategori = "ev-yasam",
                            Marka = "Philips",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 234
                        },
                        new
                        {
                            Id = 19,
                            Ad = "Bellona 3lü Koltuk Takımı",
                            AltKategori = "Mobilya",
                            Fiyat = 24999m,
                            Gorsel = "/IMG/urun/Dyson-V15-Detect_1-removebg-preview.png",
                            IndirimFiyat = 19999m,
                            IndirimYuzde = 20,
                            Kategori = "ev-yasam",
                            Marka = "Bellona",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Koçtaş LED Aydınlatma Panel",
                            AltKategori = "Aydınlatma",
                            Fiyat = 249m,
                            Gorsel = "/IMG/urun/Dyson-V15-Detect_1-removebg-preview.png",
                            IndirimFiyat = 199m,
                            IndirimYuzde = 20,
                            Kategori = "ev-yasam",
                            Marka = "Koçtaş",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 156
                        },
                        new
                        {
                            Id = 21,
                            Ad = "Karaca Tuvalet Takımı 6 Parça",
                            AltKategori = "Banyo",
                            Fiyat = 899m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 749m,
                            IndirimYuzde = 17,
                            Kategori = "ev-yasam",
                            Marka = "Karaca",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 89
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Tefal Titanium Tava Seti 5 Parça",
                            AltKategori = "Mutfak",
                            Fiyat = 2499m,
                            Gorsel = "/IMG/urun/Dyson-V15-Detect_1-removebg-preview.png",
                            IndirimFiyat = 1999m,
                            IndirimYuzde = 20,
                            Kategori = "ev-yasam",
                            Marka = "Tefal",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 312
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Madame Coco Dekoratif Vazo",
                            AltKategori = "Dekorasyon",
                            Fiyat = 179m,
                            Gorsel = "/IMG/urun/Dyson-V15-Detect_1-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "ev-yasam",
                            Marka = "Madame Coco",
                            Puan = 4.0999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 45
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Nevşah Yatak Odası Tekstil Seti",
                            AltKategori = "Yatak Odası",
                            Fiyat = 1499m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 1199m,
                            IndirimYuzde = 20,
                            Kategori = "ev-yasam",
                            Marka = "Nevşah",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 78
                        },
                        new
                        {
                            Id = 25,
                            Ad = "Ülker Çikolatalı Gofret 12li",
                            AltKategori = "Gıda",
                            Fiyat = 49m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 39m,
                            IndirimYuzde = 20,
                            Kategori = "supermarket",
                            Marka = "Ülker",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 2345
                        },
                        new
                        {
                            Id = 26,
                            Ad = "Coca Cola 1.5L 6lı Paket",
                            AltKategori = "İçecek",
                            Fiyat = 89m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 69m,
                            IndirimYuzde = 22,
                            Kategori = "supermarket",
                            Marka = "Coca Cola",
                            Puan = 4.0999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 1234
                        },
                        new
                        {
                            Id = 27,
                            Ad = "Domestos Çamaşır Suyu 2L",
                            AltKategori = "Temizlik",
                            Fiyat = 39m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 29m,
                            IndirimYuzde = 26,
                            Kategori = "supermarket",
                            Marka = "Domestos",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 567
                        },
                        new
                        {
                            Id = 28,
                            Ad = "Selpak Tuvalet Kağıdı 32li",
                            AltKategori = "Kağıt Ürünleri",
                            Fiyat = 149m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 119m,
                            IndirimYuzde = 20,
                            Kategori = "supermarket",
                            Marka = "Selpak",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 890
                        },
                        new
                        {
                            Id = 29,
                            Ad = "Fairy Bulaşık Deterjanı 700ml",
                            AltKategori = "Ev Bakım",
                            Fiyat = 69m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "supermarket",
                            Marka = "Fairy",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 678
                        },
                        new
                        {
                            Id = 30,
                            Ad = "MAC Studio Fix Fondöten",
                            AltKategori = "Makyaj",
                            Fiyat = 899m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 749m,
                            IndirimYuzde = 17,
                            Kategori = "kozmetik",
                            Marka = "MAC",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 312
                        },
                        new
                        {
                            Id = 31,
                            Ad = "L'Oréal Paris Saç Boyası",
                            AltKategori = "Saç Bakım",
                            Fiyat = 249m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 199m,
                            IndirimYuzde = 20,
                            Kategori = "kozmetik",
                            Marka = "L'Oréal",
                            Puan = 4.0999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 567
                        },
                        new
                        {
                            Id = 32,
                            Ad = "Nivea Krem 400ml Nemlendirici",
                            AltKategori = "Cilt Bakım",
                            Fiyat = 179m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 149m,
                            IndirimYuzde = 17,
                            Kategori = "kozmetik",
                            Marka = "Nivea",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 890
                        },
                        new
                        {
                            Id = 33,
                            Ad = "Armani Beauty Kırmızı Ruj",
                            AltKategori = "Makyaj",
                            Fiyat = 699m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "kozmetik",
                            Marka = "Armani",
                            Puan = 4.4000000000000004,
                            Stokta = false,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 156
                        },
                        new
                        {
                            Id = 34,
                            Ad = "Dior Sauvage Parfüm 100ml",
                            AltKategori = "Parfüm",
                            Fiyat = 2499m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 2199m,
                            IndirimYuzde = 12,
                            Kategori = "kozmetik",
                            Marka = "Dior",
                            Puan = 4.7000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 234
                        },
                        new
                        {
                            Id = 35,
                            Ad = "Nivea Vücut Losyonu 400ml",
                            AltKategori = "Vücut Bakım",
                            Fiyat = 139m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 99m,
                            IndirimYuzde = 29,
                            Kategori = "kozmetik",
                            Marka = "Nivea",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 678
                        },
                        new
                        {
                            Id = 36,
                            Ad = "Lacoste Beyaz Sneaker",
                            AltKategori = "Kadın Ayakkabı",
                            Fiyat = 2999m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 2499m,
                            IndirimYuzde = 17,
                            Kategori = "ayakkabi-canta",
                            Marka = "Lacoste",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 45
                        },
                        new
                        {
                            Id = 37,
                            Ad = "Diesel Siyah Spor Ayakkabı",
                            AltKategori = "Erkek Ayakkabı",
                            Fiyat = 3499m,
                            Gorsel = "/IMG/urun/Diesel-Spor-Ayakkab-_1_-removebg-preview.png",
                            IndirimFiyat = 2499m,
                            IndirimYuzde = 29,
                            Kategori = "ayakkabi-canta",
                            Marka = "Diesel",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 34
                        },
                        new
                        {
                            Id = 38,
                            Ad = "Nike Air Max 90 Beyaz",
                            AltKategori = "Spor Ayakkabı",
                            Fiyat = 3299m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 2799m,
                            IndirimYuzde = 15,
                            Kategori = "ayakkabi-canta",
                            Marka = "Nike",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 156
                        },
                        new
                        {
                            Id = 39,
                            Ad = "Michael Kors Siyah Çanta",
                            AltKategori = "Çanta",
                            Fiyat = 4999m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 3999m,
                            IndirimYuzde = 20,
                            Kategori = "ayakkabi-canta",
                            Marka = "Michael Kors",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 89
                        },
                        new
                        {
                            Id = 40,
                            Ad = "Crocs Terlik Siyah",
                            AltKategori = "Terlik",
                            Fiyat = 499m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 399m,
                            IndirimYuzde = 20,
                            Kategori = "ayakkabi-canta",
                            Marka = "Crocs",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 234
                        },
                        new
                        {
                            Id = 41,
                            Ad = "iPhone 15 Pro Max 256GB",
                            AltKategori = "Telefon",
                            Fiyat = 59999m,
                            Gorsel = "/IMG/urun/apple-iphone-15-pro-max_1-removebg-preview.png",
                            IndirimFiyat = 54999m,
                            IndirimYuzde = 8,
                            Kategori = "elektronik",
                            Marka = "Apple",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 128
                        },
                        new
                        {
                            Id = 42,
                            Ad = "Samsung Galaxy S24 Ultra 512GB",
                            AltKategori = "Telefon",
                            Fiyat = 52999m,
                            Gorsel = "/IMG/urun/Samsung-Galaxy-S24-Ultra.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "elektronik",
                            Marka = "Samsung",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 95
                        },
                        new
                        {
                            Id = 43,
                            Ad = "Apple MacBook Pro M3 Max 16\"",
                            AltKategori = "Bilgisayar",
                            Fiyat = 89999m,
                            Gorsel = "/IMG/urun/Apple-MacBook-Pro-M3_1__1_-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "elektronik",
                            Marka = "Apple",
                            Puan = 4.7000000000000002,
                            Stokta = false,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 44,
                            Ad = "Dell XPS 15 OLED i9 32GB",
                            AltKategori = "Bilgisayar",
                            Fiyat = 45999m,
                            Gorsel = "/IMG/urun/Dell-XPS-15_1-removebg-preview.png",
                            IndirimFiyat = 42999m,
                            IndirimYuzde = 7,
                            Kategori = "elektronik",
                            Marka = "Dell",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 45
                        },
                        new
                        {
                            Id = 45,
                            Ad = "Samsung Galaxy Tab S9 FE",
                            AltKategori = "Tablet",
                            Fiyat = 15999m,
                            Gorsel = "/IMG/urun/Galaxy-Tab-S9-FE_1__1-removebg-preview.png",
                            IndirimFiyat = 13999m,
                            IndirimYuzde = 13,
                            Kategori = "elektronik",
                            Marka = "Samsung",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 89
                        },
                        new
                        {
                            Id = 46,
                            Ad = "Sony WH-1000XM5 Gürültü Önleyici",
                            AltKategori = "Kulaklık",
                            Fiyat = 8499m,
                            Gorsel = "/IMG/urun/Sony-WH-1000XM5_1-removebg-preview.png",
                            IndirimFiyat = 7499m,
                            IndirimYuzde = 12,
                            Kategori = "elektronik",
                            Marka = "Sony",
                            Puan = 4.7999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 256
                        },
                        new
                        {
                            Id = 47,
                            Ad = "Apple AirPods Pro 2. Nesil",
                            AltKategori = "Kulaklık",
                            Fiyat = 7999m,
                            Gorsel = "/IMG/urun/Apple-AirPods-Pro-2-_1_-removebg-preview.png",
                            IndirimFiyat = 7299m,
                            IndirimYuzde = 9,
                            Kategori = "elektronik",
                            Marka = "Apple",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 312
                        },
                        new
                        {
                            Id = 48,
                            Ad = "Sony PlayStation 5 Pro 2TB",
                            AltKategori = "Oyun",
                            Fiyat = 29999m,
                            Gorsel = "/IMG/urun/PlayStation-5-Pro_1-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "elektronik",
                            Marka = "Sony",
                            Puan = 4.9000000000000004,
                            Stokta = false,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 423
                        },
                        new
                        {
                            Id = 49,
                            Ad = "Samsung 75\" Neo QLED 8K TV",
                            AltKategori = "Telefon",
                            Fiyat = 149999m,
                            Gorsel = "/IMG/urun/Samsung-75-_1_-removebg-preview.png",
                            IndirimFiyat = 129999m,
                            IndirimYuzde = 13,
                            Kategori = "elektronik",
                            Marka = "Samsung",
                            Puan = 4.7000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 50,
                            Ad = "Bose QuietComfort Ultra Kulaklık",
                            AltKategori = "Kulaklık",
                            Fiyat = 9499m,
                            Gorsel = "/IMG/urun/Bose-QuietComfort-Ultra_1-removebg-preview.png",
                            IndirimFiyat = 8499m,
                            IndirimYuzde = 11,
                            Kategori = "elektronik",
                            Marka = "Bose",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 134
                        },
                        new
                        {
                            Id = 51,
                            Ad = "Casio G-Shock Dijital Kol Saati",
                            AltKategori = "Kol Saati",
                            Fiyat = 1499m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 1199m,
                            IndirimYuzde = 20,
                            Kategori = "saat-aksesuar",
                            Marka = "Casio",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 234
                        },
                        new
                        {
                            Id = 52,
                            Ad = "Swiss Canon Altın Kolye",
                            AltKategori = "Takı",
                            Fiyat = 2999m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "saat-aksesuar",
                            Marka = "Swiss Canon",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 78
                        },
                        new
                        {
                            Id = 53,
                            Ad = "Polaroid Güneş Gözlüğü",
                            AltKategori = "Gözlük",
                            Fiyat = 699m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 499m,
                            IndirimYuzde = 29,
                            Kategori = "saat-aksesuar",
                            Marka = "Polaroid",
                            Puan = 4.2000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 145
                        },
                        new
                        {
                            Id = 54,
                            Ad = "Hugo Boss Siyah Kemer",
                            AltKategori = "Kemer",
                            Fiyat = 899m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 749m,
                            IndirimYuzde = 17,
                            Kategori = "saat-aksesuar",
                            Marka = "Hugo Boss",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 55,
                            Ad = "Pierre Cardin Erkek Cüzdan",
                            AltKategori = "Cüzdan",
                            Fiyat = 399m,
                            Gorsel = "/IMG/urun/Polo_1-removebg-preview.png",
                            IndirimFiyat = 299m,
                            IndirimYuzde = 25,
                            Kategori = "saat-aksesuar",
                            Marka = "Pierre Cardin",
                            Puan = 4.0999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 156
                        },
                        new
                        {
                            Id = 56,
                            Ad = "Adidas Originals Erkek Eşofman",
                            AltKategori = "Spor Giyim",
                            Fiyat = 1299m,
                            Gorsel = "/IMG/urun/Diesel-Spor-Ayakkab-_1_-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "spor-outdoor",
                            Marka = "Adidas",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 67
                        },
                        new
                        {
                            Id = 57,
                            Ad = "Under Armour Spor Tayt Siyah",
                            AltKategori = "Spor Giyim",
                            Fiyat = 899m,
                            Gorsel = "/IMG/urun/Diesel-Spor-Ayakkab-_1_-removebg-preview.png",
                            IndirimFiyat = 599m,
                            IndirimYuzde = 33,
                            Kategori = "spor-outdoor",
                            Marka = "Under Armour",
                            Puan = 4.2999999999999998,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 78
                        },
                        new
                        {
                            Id = 58,
                            Ad = "Nike Yoga Mat 6mm",
                            AltKategori = "Fitness",
                            Fiyat = 599m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 0m,
                            IndirimYuzde = 0,
                            Kategori = "spor-outdoor",
                            Marka = "Nike",
                            Puan = 4.4000000000000004,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 234
                        },
                        new
                        {
                            Id = 59,
                            Ad = "The North Face Sırt Çantası 50L",
                            AltKategori = "Kamp",
                            Fiyat = 2999m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 2499m,
                            IndirimYuzde = 17,
                            Kategori = "spor-outdoor",
                            Marka = "The North Face",
                            Puan = 4.7000000000000002,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 145
                        },
                        new
                        {
                            Id = 60,
                            Ad = "Salomon Su Geçirmez Mont",
                            AltKategori = "Kamp",
                            Fiyat = 3999m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 2999m,
                            IndirimYuzde = 25,
                            Kategori = "spor-outdoor",
                            Marka = "Salomon",
                            Puan = 4.5999999999999996,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = true,
                            YorumSayisi = 56
                        },
                        new
                        {
                            Id = 61,
                            Ad = "Bisiklet Kaskı MIPS Korumalı",
                            AltKategori = "Bisiklet",
                            Fiyat = 899m,
                            Gorsel = "/IMG/urun/Lacoste-Sneaker_1__1_-removebg-preview.png",
                            IndirimFiyat = 749m,
                            IndirimYuzde = 17,
                            Kategori = "spor-outdoor",
                            Marka = "Salcano",
                            Puan = 4.5,
                            Stokta = true,
                            TaksitAylikFiyat = 0m,
                            TaksitSayisi = 0,
                            UcretsizKargo = false,
                            YorumSayisi = 89
                        });
                });

            modelBuilder.Entity("backend.Models.SiparisDetay", b =>
                {
                    b.HasOne("backend.Models.Siparis", "Siparis")
                        .WithMany("Detaylar")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("backend.Models.Siparis", b =>
                {
                    b.Navigation("Detaylar");
                });
#pragma warning restore 612, 618
        }
    }
}
